version: '3.5'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .\cloud_project\cloud:/code/cloud
      - .\cloud_project\myproject:/code/myproject
    ports:
    - "8000:8000"
